Fix error when trying to Initialize Maestro with il2cpp
NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: Maestro.MaestroManager::<.ctor>b__13_0

# Conflicts:
#	maestro-unity/Maestro.cs